site_name: C++ Project Template
site_dir: site
repo_url: https://eng.plexus.com/git/projects/EP/repos/cpp-project-template/browse
repo_name: Bitbucket

theme:
  name: material
  features:
    - navigation.sections
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:
      generic: true
  - plantuml_markdown
plugins:
  - search
  - ezlinks
  - mermaid2:
      version: 8.9.2
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
  - monorepo
  - awesome-pages
nav:
  - Introduction: index.md
  - Host Environment: host_environment.md
  - Project Definition: project_definition.md
  - Editing and Building: edit_build.md
  - Debugging: debugging.md
  - Unit Testing: unit_testing.md
  - Static Analysis: static_analysis.md
  - Documentation Generation: doc_gen.md
  - Code Styling: code_styling.md
