function(sublist_entirely_contained_within_superlist SUBLIST SUPERLIST RESULT)
    set(${RESULT} TRUE PARENT_SCOPE)
    foreach(ITEM IN LISTS SUBLIST)
        list(FIND SUPERLIST "${ITEM}" INDEX)
        if(INDEX EQUAL -1)
        set(${RESULT} FALSE PARENT_SCOPE)
            break()
        endif()
    endforeach()
endfunction()

function(convert_list_to_lines LIST)
    set(CONTENTS "")
    foreach(line ${${LIST}})
        set(CONTENTS "${CONTENTS}${line}\n")
    endforeach()
    set(${LIST} ${CONTENTS} PARENT_SCOPE)
endfunction()

function(write_list_to_file LIST FILE MODE)
    convert_list_to_lines(${LIST})
    file("${MODE}" "${FILE}" "${${LIST}}")
endfunction()
