function(tokenize INPUT_STRING DELIMITER OUTPUT_LIST)
    set(RESULT_LIST)
    string(REGEX REPLACE "${DELIMITER}" ";" TEMP_STRING "${INPUT_STRING}")
    foreach(ITEM ${TEMP_STRING})
        list(APPEND RESULT_LIST "${ITEM}")
    endforeach()
    set(${OUTPUT_LIST} ${RESULT_LIST} PARENT_SCOPE)
endfunction()

function(number_of_char_instances_in_string STR CHAR NUM)
    string(REGEX REPLACE "\\${CHAR}" "" NEW_STR "${STR}")
    string(LENGTH "${STR}" STR_LEN)
    string(LENGTH "${NEW_STR}" NEW_STR_LEN)
    math(EXPR COUNT "${STR_LEN} - ${NEW_STR_LEN}")
    set(${NUM} ${COUNT} PARENT_SCOPE)
endfunction()

function(string_contains_any STR SUBSTRINGS RESULT)
    set(VAL FALSE)
    foreach(SUBSTRING IN LISTS SUBSTRINGS)
        string(FIND "${STR}" "${SUBSTRING}" INDEX)
        if(NOT INDEX EQUAL -1)
            set(VAL TRUE)
            break()
        endif()
    endforeach()
    set(${RESULT} "${VAL}" PARENT_SCOPE)
endfunction()

function(string_starts_with STR SEARCH RESULT)
    string(FIND "${STR}" "${SEARCH}" OUT)
    if("${OUT}" EQUAL 0)
        set(${RESULT} "TRUE" PARENT_SCOPE)
    else()
        set(${RESULT} "FALSE" PARENT_SCOPE)
    endif()
endfunction()
